# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfca627b3f70d2c8f21a50a5e216dc7ab11eb3c37abf06beca357e302b51e852c93a04b0098279473e56b78a26140662f873a367accc0533eb83c93a4418afc1

test:
  secret_key_base: a8c47b7ea81d4b29987461e7674c666b37aaf58d71d9e1c5cdd37a3a2345fb705f280adcbc60dea3cad13bf9e7afb6bada50ce941052c69991ab2c8efac8e8fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
